import { Props } from './AuthorCard.vue';
export const heatSurgeData: Props[] = [
  {
    top: 1,
    avatarImg: '/avatar.webp',
    name: '亚比囧囧囧',
    hot: 456,
    isUpDown: 'up',
  },
  {
    top: 2,
    avatarImg: '/avatar.webp',
    name: '白开水',
    hot: 123,
    isUpDown: 'up',
  },
  {
    top: 3,
    avatarImg: '/avatar.webp',
    name: '黑关土',
    hot: 111,
    isUpDown: 'up',
  },
  {
    top: 4,
    avatarImg: '/avatar.webp',
    name: '白开水',
    hot: 123,
    isUpDown: 'up',
  },
  {
    top: 5,
    avatarImg: '/avatar.webp',
    name: '黑关土',
    hot: 111,
    isUpDown: 'up',
  },
  {
    top: 6,
    avatarImg: '/avatar.webp',
    name: '白开水',
    hot: 123,
    isUpDown: 'up',
  },
  {
    top: 7,
    avatarImg: '/avatar.webp',
    name: '黑关土',
    hot: 111,
    isUpDown: 'up',
  },
  {
    top: 8,
    avatarImg: '/avatar.webp',
    name: '白开水',
    hot: 123,
    isUpDown: 'up',
  },
  {
    top: 9,
    avatarImg: '/avatar.webp',
    name: '黑关土',
    hot: 111,
    isUpDown: 'up',
  },
  {
    top: 10,
    avatarImg: '/avatar.webp',
    name: '白开水',
    hot: 123,
    isUpDown: 'up',
  },
  {
    top: 11,
    avatarImg: '/avatar.webp',
    name: '黑关土',
    hot: 111,
    isUpDown: 'up',
  },
  {
    top: 12,
    avatarImg: '/avatar.webp',
    name: '白开水',
    hot: 123,
    isUpDown: 'up',
  },
  {
    top: 13,
    avatarImg: '/avatar.webp',
    name: '黑关土',
    hot: 111,
    isUpDown: 'up',
  },
];
